[tool.poetry]
name = "analysis-tools"
version = "0.1.0"
description = "Model training and analysis tools"
authors = ["Anthony Sacco <asacco@plymouthrock.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
pandas = "==2.3.1"
numpy = "==2.3.2"
scikit-learn = "==1.7.1"
matplotlib = "==3.10.3"
seaborn = "==0.13.2"
pyyaml = "==6.0.2"
xgboost = "==3.0.2"
boto3 = "==1.39.15"
optuna = "^4.4.0"
plotly = "^6.2.0"
nbformat = "^5.10.4"

[tool.poetry.group.dev.dependencies]
jupyterlab = "*"
ipython = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


