"""HTML reporting utilities for assembling analysis reports."""
from __future__ import annotations

from typing import Any, Callable, Iterable, List, Optional

import pandas as pd

from . import plots, tabulation
from .utils import fig_to_html


class ModelAnalysisReport:
    """Flexible builder for model analysis reports."""

    def __init__(
        self,
        df: pd.DataFrame,
        actual_col: str,
        predicted_col: str,
        *,
        split_col: str = "split",
        exposure_col: str | None = None,
        title: str | None = None,
    ) -> None:
        self.df = df.copy()
        self.actual_col = actual_col
        self.predicted_col = predicted_col
        self.split_col = split_col
        self.exposure_col = exposure_col
        self.title = title
        self._sections: List[str] = []

    # ------------------------------------------------------------------
    # Metric helpers formerly provided by ModelEvaluator
    def mse(self) -> float:
        """Return mean squared error."""
        return float(((self.df[self.actual_col] - self.df[self.predicted_col]) ** 2).mean())

    def mae(self) -> float:
        """Return mean absolute error."""
        return float((self.df[self.actual_col] - self.df[self.predicted_col]).abs().mean())

    def dislocation(self) -> pd.Series:
        """Return the difference between actuals and predictions."""
        return self.df[self.actual_col] - self.df[self.predicted_col]

    # ------------------------------------------------------------------
    # Convenience plotting helpers
    def plot_gain(self, **kwargs: Any) -> Any:
        return plots.gain_curve_with_gini(
            self.df,
            self.actual_col,
            self.predicted_col,
            exposure_col=self.exposure_col,
            split_name=None,
            **kwargs,
        )

    def plot_lift(self, **kwargs: Any) -> Any:
        return plots.lift_chart(
            self.df,
            self.actual_col,
            self.predicted_col,
            exposure_col=self.exposure_col,
            split_name=None,
            **kwargs,
        )

    def plot_residuals(self, **kwargs: Any) -> Any:
        return plots.crunched_residual_plot(
            self.df,
            self.actual_col,
            self.predicted_col,
            exposure_col=self.exposure_col,
            split_name=None,
            **kwargs,
        )

    def plot_partial_gini(self, top_percent: int = 20, **kwargs: Any) -> Any:
        return plots.partial_gini_plot(
            self.df,
            self.actual_col,
            self.predicted_col,
            exposure_col=self.exposure_col,
            split_name=None,
            top_percent=top_percent,
            **kwargs,
        )

    def plot_error_by_group_grid(self, group_cols: Iterable[str], **kwargs: Any) -> Any:
        return plots.plot_error_by_group_grid(
            self.df,
            self.actual_col,
            self.predicted_col,
            group_cols=group_cols,
            **kwargs,
        )

    # ------------------------------------------------------------------
    def compare_models_discrepancy(
        self, other_pred_col: str, n: int = 10, by: Optional[Iterable[str]] = None
    ) -> pd.DataFrame:
        cols = [self.actual_col, self.predicted_col, other_pred_col]
        if by:
            cols.extend(by)
        df = self.df[cols].copy()
        df["abs_diff"] = (df[self.predicted_col] - df[other_pred_col]).abs()
        return df.nlargest(n, "abs_diff")

    # ------------------------------------------------------------------
    def to_html(self) -> str:
        """Return the assembled HTML report as a string."""
        html_output = "<h1>Model Analysis Report</h1>"
        html_output += "".join(self._sections)
        return html_output

    # Jupyter will use this method to display HTML representation
    def _repr_html_(self) -> str:  # pragma: no cover - simple passthrough
        return self.to_html()

    # ------------------------------------------------------------------
    def add_plot(self, plot_func: Callable[..., Any], heading: str, **kwargs: Any) -> None:
        """Add a section generated by ``plot_func`` for each data split."""
        html = f"<h2>{heading}</h2><div style='display:flex;flex-wrap:wrap'>"
        for split_value in self.df[self.split_col].unique():
            df_split = self.df[self.df[self.split_col] == split_value].copy()
            fig = plot_func(
                df=df_split,
                actual_col=self.actual_col,
                predicted_col=self.predicted_col,
                exposure_col=self.exposure_col,
                split_name=split_value,
                title=self.title,
                **kwargs,
            )
            html += f"<div style='margin:10px'><h4>{split_value} Split</h4>{fig_to_html(fig)}</div>"
        html += "</div>"
        self._sections.append(html)

    def add_tabulation(self, variables: Iterable[str], **kwargs: Any) -> None:
        """Add a tabulation section for ``variables``."""
        html = "<h2>Tabulations</h2>"
        html += tabulation.generate_tabulations_html(
            self.df,
            prediction_col=self.predicted_col,
            truth_col=self.actual_col,
            group_vars=list(variables),
            split_col=self.split_col,
            weights_col=self.exposure_col,
            **kwargs,
        )
        self._sections.append(html)

    # ------------------------------------------------------------------
    def export_html(
        self,
        output_html: str = "model_analysis.html",
        title: str | None = None,
        *,
        error_group_cols: Iterable[str] | None = None,
        tabulation_vars: Iterable[str] | None = None,
        gain_kwargs: dict[str, Any] | None = None,
        lift_kwargs: dict[str, Any] | None = None,
        residual_kwargs: dict[str, Any] | None = None,
        residual_fit_kwargs: dict[str, Any] | None = None,
    ) -> None:
        generate_model_analysis_report(
            self.df,
            self.actual_col,
            self.predicted_col,
            split_col=self.split_col,
            exposure_col=self.exposure_col,
            output_html=output_html,
            error_group_cols=error_group_cols,
            tabulation_vars=tabulation_vars,
            title=title,
            gain_kwargs=gain_kwargs,
            lift_kwargs=lift_kwargs,
            residual_kwargs=residual_kwargs,
            residual_fit_kwargs=residual_fit_kwargs,
        )

    def tabulate(
        self,
        group_vars: Iterable[str],
        *,
        output_html: str,
        n_bins: int = 5,
        factor: bool = False,
    ) -> str | None:
        tabulation.generate_and_save_tabulations(
            df=self.df,
            prediction_col=self.predicted_col,
            truth_col=self.actual_col,
            group_vars=list(group_vars),
            split_col=self.split_col,
            weights_col=self.exposure_col,
            n_bins=n_bins,
            factor=factor,
            output_html=output_html,
        )
        return None

    def save(self, output_html: str = "model_analysis.html") -> None:
        """Write the assembled report to ``output_html``."""
        html_output = "<html><head><title>Model Analysis Report</title></head><body>"
        html_output += self.to_html()
        html_output += "</body></html>"
        with open(output_html, "w") as f:
            f.write(html_output)
        print(f"✅ Analysis report generated at {output_html}")


# ----------------------------------------------------------------------
# Backwards compatible function

def generate_model_analysis_report(
    df: pd.DataFrame,
    actual_col: str,
    predicted_col: str,
    split_col: str = "split",
    exposure_col: str | None = None,
    output_html: str = "model_analysis.html",
    gain_kwargs: dict[str, Any] | None = None,
    lift_kwargs: dict[str, Any] | None = None,
    residual_kwargs: dict[str, Any] | None = None,
    residual_fit_kwargs: dict[str, Any] | None = None,
    error_group_cols: Iterable[str] | None = None,
    tabulation_vars: Iterable[str] | None = None,
    title: str | None = None,
) -> None:
    """Generate a full HTML model analysis report using :class:`ModelAnalysisReport`."""
    gain_kwargs = gain_kwargs or {}
    lift_kwargs = lift_kwargs or {}
    residual_kwargs = residual_kwargs or {}
    residual_fit_kwargs = residual_fit_kwargs or {}

    report = ModelAnalysisReport(
        df,
        actual_col,
        predicted_col,
        split_col=split_col,
        exposure_col=exposure_col,
        title=title,
    )

    report.add_plot(plots.gain_curve_with_gini, "Gain Curve / Lorenz Curve with Gini", **gain_kwargs)
    report.add_plot(plots.lift_chart, "Lift Charts", **lift_kwargs)
    report.add_plot(plots.crunched_residual_plot, "Crunched Residual Plots", **residual_kwargs)
    report.add_plot(plots.plot_residual_fit, "Avg. and Std. of Deviance Residuals Plots", **residual_fit_kwargs)

    if error_group_cols:
        report.add_plot(
            lambda d, a, p, e, split_name=None, title=None, **k: plots.plot_error_by_group_grid(
                d, a, p, error_group_cols, **k
            ),
            "Error by Group",
        )

    if tabulation_vars:
        report.add_tabulation(tabulation_vars)

    report.save(output_html)
